In [ ]:
import os
import numpy as np

def obtener_value_counts_ultrarapido(carpeta_dataset):
    
    conteo_global = np.zeros(19, dtype=np.int64)
    contador_archivos = 0
    
    with os.scandir(carpeta_dataset) as it:
        for entrada in it:
            if entrada.is_file() and entrada.name.endswith('_Y.npy'):
                contador_archivos += 1
                
                if contador_archivos % 25000 == 0:
                    print(f"Progreso: {contador_archivos:} archivos procesados...")
                
                try:
                    parche_y = np.load(entrada.path)
                    conteos = np.bincount(parche_y.ravel() minlength=19)
                    conteo_global += conteos[:19]
                except Exception:
                    continue

    if contador_archivos == 0:
        print(f"No se encontraron archivos _Y.npy en {carpeta_dataset}")
        return

    print("\n" + "="*40)
    print("      CONTEO DE PÍXELES POR CLASE")
    print("="*40)
    print(f"{'Clase':<10}{'Número de Píxeles':<20}{'Porcentaje':<12}")
    print("-"*40)
    
    total_pixeles = np.sum(conteo_global)
    for clase total in enumerate(conteo_global):
        porcentaje = (total / total_pixeles) * 100 if total_pixeles > 0 else 0
        print(f"{clase:<10}{total:<20,}{porcentaje:<12.4f}%")
    print("="*40)

if __name__ == '__main__':
    carpeta_tfg = r"D:\TFG\dataset_parches_50x50" 
    obtener_value_counts_ultrarapido(carpeta_tfg)

Abriendo la carpeta y escaneando archivos en tiempo real...
Progreso: 25,000 archivos procesados...
Progreso: 50,000 archivos procesados...
Progreso: 75,000 archivos procesados...
Progreso: 100,000 archivos procesados...
Progreso: 125,000 archivos procesados...
Progreso: 150,000 archivos procesados...
Progreso: 175,000 archivos procesados...
Progreso: 200,000 archivos procesados...
Progreso: 225,000 archivos procesados...
Progreso: 250,000 archivos procesados...
Progreso: 275,000 archivos procesados...
Progreso: 300,000 archivos procesados...
Progreso: 325,000 archivos procesados...
Progreso: 350,000 archivos procesados...
Progreso: 375,000 archivos procesados...
Progreso: 400,000 archivos procesados...
Progreso: 425,000 archivos procesados...
Progreso: 450,000 archivos procesados...
Progreso: 475,000 archivos procesados...
Progreso: 500,000 archivos procesados...
Progreso: 525,000 archivos procesados...
Progreso: 550,000 archivos procesados...
Progreso: 575,000 archivos procesados...


In [7]:
import numpy as np
clases = [[0,39551845],[1,13388531],[2,925335116],[3,228351969],[4,48133035],[5,120528133],[6,83941750],[7,110880810],[11,4589]]
np.sum(clases, axis=0)[1]

1570115778

In [8]:
import os
import numpy as np

carpeta_dataset = r"D:\TFG\dataset_parches_50x50"

# 1. Tomar los primeros 20 archivos de etiquetas como muestra
archivos_Y = [f for f in os.listdir(carpeta_dataset) if f.endswith('_Y.npy')][:20]

print("=== ANALIZANDO VALORES EXTENDIDOS EN LOS ARCHIVOS ===")
valores_unicos_globales = set()
encontrado_negativo = False

for archivo in archivos_Y:
    parche_y = np.load(os.path.join(carpeta_dataset, archivo))
    
    # Añadimos los valores únicos de este parche al conjunto global
    valores_unicos_globales.update(np.unique(parche_y))
    
    # Comprobamos si hay algún valor menor que 0
    if np.any(parche_y < 0):
        encontrado_negativo = True
        print(f"¡Alerta! Archivo con negativos detectado: {archivo}")
        print(f" -> Valor mínimo en este archivo: {parche_y.min()}")

print("\n" + "="*40)
if encontrado_negativo:
    print("RESULTADO: SÍ hay números negativos en las matrices.")
else:
    print("RESULTADO: No se encontraron números negativos en esta muestra.")

print(f"Todos los valores numéricos distintos encontrados: {sorted(list(valores_unicos_globales))}")
print("="*40)

=== ANALIZANDO VALORES EXTENDIDOS EN LOS ARCHIVOS ===

RESULTADO: No se encontraron números negativos en esta muestra.
Todos los valores numéricos distintos encontrados: [5, 19]


In [10]:
import os
import numpy as np

def obtener_conteos_duples_ultrarapido(carpeta_dataset):
    conteo_global_pixeles = np.zeros(20, dtype=np.int64)
    conteo_parches_dominantes = np.zeros(20, dtype=np.int64)
    contador_archivos = 0
    
    with os.scandir(carpeta_dataset) as it:
        for entrada in it:
            if entrada.is_file() and entrada.name.endswith('_Y.npy'):
                contador_archivos += 1
                
                if contador_archivos % 25000 == 0:
                    print(f"Progreso: {contador_archivos:,} archivos procesados...", flush=True)
                
                try:
                    parche_y = np.load(entrada.path)
                    conteos_un_parche = np.bincount(parche_y.ravel(), minlength=20)
                    
                    # 1. Acumulamos para el conteo global de píxeles
                    conteo_global_pixeles += conteos_un_parche[:20]
                    
                    # 2. Calculamos la clase dominante de este parche y acumulamos
                    clase_ganadora = np.argmax(conteos_un_parche[:20])
                    conteo_parches_dominantes[clase_ganadora] += 1
                    
                except Exception:
                    continue

    if contador_archivos == 0:
        print(f"No se encontraron archivos _Y.npy en {carpeta_dataset}", flush=True)
        return

    # --- TABLA 1: CONTEO GLOBAL DE PÍXELES ---
    print("\n" + "="*40, flush=True)
    print("      CONTEO DE PÍXELES POR CLASE")
    print("="*40, flush=True)
    print(f"{'Clase':<10}{'Número de Píxeles':<20}{'Porcentaje':<12}", flush=True)
    print("-"*40, flush=True)
    total_pixeles = np.sum(conteo_global_pixeles)
    for clase, total in enumerate(conteo_global_pixeles):
        porcentaje = (total / total_pixeles) * 100 if total_pixeles > 0 else 0
        print(f"{clase:<10}{total:<20,}{porcentaje:<12.4f}%", flush=True)
        
    # --- TABLA 2: PARCHES DOMINANTES ---
    print("\n" + "="*40, flush=True)
    print("   DISTRIBUCIÓN DE PARCHES POR CLASE DOMINANTE")
    print("="*40, flush=True)
    print(f"{'Clase':<10}{'Número de Parches':<20}{'Porcentaje':<12}", flush=True)
    print("-"*40, flush=True)
    total_parches_validos = np.sum(conteo_parches_dominantes)
    for clase, total in enumerate(conteo_parches_dominantes):
        porcentaje = (total / total_parches_validos) * 100 if total_parches_validos > 0 else 0
        print(f"{clase:<10}{total:<20,}{porcentaje:<12.4f}%", flush=True)
    print("="*40, flush=True)

if __name__ == '__main__':
    carpeta_tfg = r"D:\TFG\dataset_parches_50x50" 
    obtener_conteos_duples_ultrarapido(carpeta_tfg)

Progreso: 25,000 archivos procesados...
Progreso: 50,000 archivos procesados...
Progreso: 75,000 archivos procesados...
Progreso: 100,000 archivos procesados...
Progreso: 125,000 archivos procesados...
Progreso: 150,000 archivos procesados...
Progreso: 175,000 archivos procesados...
Progreso: 200,000 archivos procesados...
Progreso: 225,000 archivos procesados...
Progreso: 250,000 archivos procesados...
Progreso: 275,000 archivos procesados...
Progreso: 300,000 archivos procesados...
Progreso: 325,000 archivos procesados...
Progreso: 350,000 archivos procesados...
Progreso: 375,000 archivos procesados...
Progreso: 400,000 archivos procesados...
Progreso: 425,000 archivos procesados...
Progreso: 450,000 archivos procesados...
Progreso: 475,000 archivos procesados...
Progreso: 500,000 archivos procesados...
Progreso: 525,000 archivos procesados...
Progreso: 550,000 archivos procesados...
Progreso: 575,000 archivos procesados...
Progreso: 600,000 archivos procesados...
Progreso: 625,000 a

In [11]:
import os
import numpy as np

def buscar_y_mostrar_primer_no_data(carpeta_dataset):
    print("Buscando el primer parche dominado por la Clase 19 (No Data)...", flush=True)
    
    with os.scandir(carpeta_dataset) as it:
        for entrada in it:
            if entrada.is_file() and entrada.name.endswith('_Y.npy'):
                try:
                    parche_y = np.load(entrada.path)
                    
                    # Contamos los píxeles (tamaño 50x50 = 2500 píxeles)
                    conteos = np.bincount(parche_y.ravel(), minlength=20)
                    
                    # Si la clase con más píxeles es la 19, lo hemos encontrado
                    if np.argmax(conteos) == 19:
                        print(f"\n¡Encontrado! Archivo: {entrada.name}")
                        print(f"Dimensiones de la matriz: {parche_y.shape}")
                        print(f"Número de píxeles con valor 19: {conteos[19]} de {parche_y.size}")
                        print("-" * 50)
                        print("IMPRIMIENDO MATRIZ COMPLETA (50x50):")
                        print("-" * 50)
                        
                        # Configuramos NumPy para que no recorte la matriz al imprimirla
                        with np.printoptions(threshold=np.inf, linewidth=200):
                            print(parche_y)
                            
                        print("-" * 50)
                        return # Detiene el programa tras encontrar el primero
                        
                except Exception as e:
                    continue
                    
    print("No se encontró ningún parche dominado por la clase 19 en la carpeta.")

if __name__ == '__main__':
    carpeta_tfg = r"D:\TFG\dataset_parches_50x50"
    buscar_y_mostrar_primer_no_data(carpeta_tfg)

Buscando el primer parche dominado por la Clase 19 (No Data)...

¡Encontrado! Archivo: parche_000255_Y.npy
Dimensiones de la matriz: (50, 50)
Número de píxeles con valor 19: 2385 de 2500
--------------------------------------------------
IMPRIMIENDO MATRIZ COMPLETA (50x50):
--------------------------------------------------
[[ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5  5 19 19 19  5  5  5  5  5  5  5  5  5 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19]
 [ 5  5  5  5  5  5  5  5  5  5  5  5  5  5 19 19 19 19  5  5  5  5  5  5  5 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19]
 [ 5  5  5  5  5  5  5  5  5  5  5  5 19 19 19 19 19 19  5  5  5  5  5 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19]
 [ 5  5  5  5  5  5  5 19 19 19 19 19 19 19 19 19 19 19 19  5 